basePath: /
definitions:
  filesmanager.Content:
    properties:
      content:
        items:
          type: integer
        type: array
      ftype:
        type: string
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  filesmanager.Dir:
    properties:
      name:
        type: string
      path:
        type: string
    type: object
  service.AddTagsRequest:
    properties:
      Path:
        type: string
      Tags:
        items:
          type: string
        type: array
    type: object
  service.FileByte:
    properties:
      content:
        items:
          type: integer
        type: array
      fileName:
        type: string
    type: object
  service.FilesResponce:
    properties:
      files:
        items:
          $ref: '#/definitions/filesmanager.Content'
        type: array
      tagsInDir:
        items:
          type: string
        type: array
    type: object
  service.Responce:
    properties:
      comment:
        type: string
      status:
        type: integer
    type: object
  service.ResponceDirs:
    properties:
      dirs:
        items:
          $ref: '#/definitions/filesmanager.Dir'
        type: array
    type: object
  service.ResponceError:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  service.ResponceFile:
    properties:
      filName:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  service.SearchInDirRequest:
    properties:
      dir:
        type: string
      tag:
        items:
          type: string
        type: array
    type: object
  service.SearchRequest:
    properties:
      tag:
        items:
          type: string
        type: array
    type: object
  service.SearchResponce:
    properties:
      files:
        items:
          $ref: '#/definitions/filesmanager.Content'
        type: array
    type: object
  settingmodule.Setting:
    properties:
      BasePath:
        type: string
      LastDir:
        type: string
      Port:
        type: string
    type: object
host: localhost:8050
info:
  contact: {}
  description: FilesWithTag API
  title: FilesWithTag API
  version: "2.0"
paths:
  /AddMeta:
    post:
      consumes:
      - application/json
      description: Добавление тегов по пути до файла
      operationId: addTags
      parameters:
      - description: path
        in: body
        name: AddTagsRequest
        required: true
        schema:
          $ref: '#/definitions/service.AddTagsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: tags
          schema:
            $ref: '#/definitions/service.Responce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Добавление тегов
      tags:
      - file
  /DelMeta:
    post:
      consumes:
      - application/json
      description: Удаление тегов по пути до файла
      operationId: delTags
      parameters:
      - description: path
        in: body
        name: AddTagsRequest
        required: true
        schema:
          $ref: '#/definitions/service.AddTagsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: tags
          schema:
            $ref: '#/definitions/service.Responce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Удаление тегов
      tags:
      - file
  /Dirs:
    get:
      consumes:
      - application/json
      description: Папки в папке
      operationId: getDirs
      parameters:
      - description: Путь до папки
        in: query
        name: Path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: tags
          schema:
            $ref: '#/definitions/service.ResponceDirs'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Папки в папке
      tags:
      - dir
  /FileByte:
    get:
      consumes:
      - application/json
      description: Получение файла в формате байт строки
      operationId: GetFilesByte
      parameters:
      - description: Путь до файла
        in: query
        name: Path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: имя файла и его содержимое
          schema:
            $ref: '#/definitions/service.FileByte'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Получение файла
      tags:
      - file
  /Files:
    get:
      consumes:
      - application/json
      description: Получение тегов по пути до файла
      operationId: GetFilesInDir
      parameters:
      - description: Путь до папки
        in: query
        name: Path
        required: true
        type: string
      - description: Количество
        in: query
        name: Count
        required: true
        type: string
      - description: Отступ
        in: query
        name: Offset
        required: true
        type: string
      - description: Тип файлов
        enum:
        - Image
        - Music
        - Video
        - Text
        in: query
        name: Ftype
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: список файлов
          schema:
            $ref: '#/definitions/service.FilesResponce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Получение тегов
      tags:
      - file
  /GetMeta:
    get:
      consumes:
      - application/json
      description: Получение тегов по пути до файла
      operationId: getTags
      parameters:
      - description: path
        in: query
        name: Path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: tags
          schema:
            $ref: '#/definitions/service.ResponceFile'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Получение тегов
      tags:
      - file
  /OsTree:
    get:
      consumes:
      - application/json
      description: Дерево папок, дерево состовляется в момент старта сервера
      operationId: GetOsTree
      produces:
      - application/json
      responses:
        "200":
          description: дерево папок
          schema:
            $ref: '#/definitions/filesmanager.Dir'
      summary: Дерево папок
      tags:
      - OsTree
  /Search:
    post:
      consumes:
      - application/json
      description: Поиск по тегам начиная с базовой папки указаной в настройке
      operationId: Search
      parameters:
      - description: Путь до папки
        in: body
        name: SearchData
        required: true
        schema:
          $ref: '#/definitions/service.SearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: список файлов
          schema:
            $ref: '#/definitions/service.SearchResponce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Поиск по тегам
      tags:
      - file
  /SearchInDir:
    post:
      consumes:
      - application/json
      description: Поиск по тегам в папке
      operationId: SearchInDir
      parameters:
      - description: Путь до папки
        in: body
        name: SearchData
        required: true
        schema:
          $ref: '#/definitions/service.SearchInDirRequest'
      produces:
      - application/json
      responses:
        "200":
          description: список файлов
          schema:
            $ref: '#/definitions/service.SearchResponce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Поиск по тегам в папке
      tags:
      - file
  /Settings:
    get:
      consumes:
      - application/json
      description: Получение настроек запуска
      operationId: getSettings
      produces:
      - application/json
      responses:
        "200":
          description: settings
          schema:
            $ref: '#/definitions/settingmodule.Setting'
      summary: Получение настроек
      tags:
      - setting
    put:
      consumes:
      - application/json
      description: Получение настроек запуска
      operationId: getSettings
      parameters:
      - description: name setting
        in: query
        name: NameSetting
        required: true
        type: string
      - description: value setting
        in: query
        name: ValueSetting
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: settings
          schema:
            $ref: '#/definitions/service.Responce'
        "400":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
        "500":
          description: error
          schema:
            $ref: '#/definitions/service.ResponceError'
      summary: Получение настроек
      tags:
      - setting
swagger: "2.0"
